// Generated by gencpp from file rb_connector/rb_command.msg
// DO NOT EDIT!


#ifndef RB_CONNECTOR_MESSAGE_RB_COMMAND_H
#define RB_CONNECTOR_MESSAGE_RB_COMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rb_connector
{
template <class ContainerAllocator>
struct rb_command_
{
  typedef rb_command_<ContainerAllocator> Type;

  rb_command_()
    : header()
    , cmd()  {
    }
  rb_command_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , cmd(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _cmd_type;
  _cmd_type cmd;





  typedef boost::shared_ptr< ::rb_connector::rb_command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rb_connector::rb_command_<ContainerAllocator> const> ConstPtr;

}; // struct rb_command_

typedef ::rb_connector::rb_command_<std::allocator<void> > rb_command;

typedef boost::shared_ptr< ::rb_connector::rb_command > rb_commandPtr;
typedef boost::shared_ptr< ::rb_connector::rb_command const> rb_commandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rb_connector::rb_command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rb_connector::rb_command_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rb_connector::rb_command_<ContainerAllocator1> & lhs, const ::rb_connector::rb_command_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.cmd == rhs.cmd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rb_connector::rb_command_<ContainerAllocator1> & lhs, const ::rb_connector::rb_command_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rb_connector

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rb_connector::rb_command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rb_connector::rb_command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rb_connector::rb_command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rb_connector::rb_command_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rb_connector::rb_command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rb_connector::rb_command_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rb_connector::rb_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4276af4fed90fb499f3ed97a1942bbe3";
  }

  static const char* value(const ::rb_connector::rb_command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4276af4fed90fb49ULL;
  static const uint64_t static_value2 = 0x9f3ed97a1942bbe3ULL;
};

template<class ContainerAllocator>
struct DataType< ::rb_connector::rb_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rb_connector/rb_command";
  }

  static const char* value(const ::rb_connector::rb_command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rb_connector::rb_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# RB Command\n"
"Header   header\n"
"string   cmd\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::rb_connector::rb_command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rb_connector::rb_command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rb_command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rb_connector::rb_command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rb_connector::rb_command_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "cmd: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RB_CONNECTOR_MESSAGE_RB_COMMAND_H
