(cl:defpackage my_code-srv
  (:use )
  (:export
   "WORDCOUNT"
   "<WORDCOUNT-REQUEST>"
   "WORDCOUNT-REQUEST"
   "<WORDCOUNT-RESPONSE>"
   "WORDCOUNT-RESPONSE"
   "WORDCOUNTRESPONSE"
   "<WORDCOUNTRESPONSE-REQUEST>"
   "WORDCOUNTRESPONSE-REQUEST"
   "<WORDCOUNTRESPONSE-RESPONSE>"
   "WORDCOUNTRESPONSE-RESPONSE"
  ))

